sudo: required
services:
    - docker

before_install:
    - docker build -t rohan230/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true rohan230/frontend npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucker_name: "elasticbeanstalk-us-east-2-799532649375"
    bucker_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
